spring.application.name=taskpulse

# Server configuration (Render injects PORT dynamically)
server.port=${PORT:8080}

# Spring Data JPA & PostgreSQL / H2 configuration
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:taskpulsedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
